
import { Property } from './types';

export const mockProperties: Property[] = [
  {
    id: 1,
    title: "Modern Downtown Loft",
    description: "A stunning loft in the heart of the city, featuring floor-to-ceiling windows and a breathtaking view. Perfect for urban living.",
    property_type: "Apartment",
    listing_type: "For Sale",
    start_price: 750000,
    status: "Active",
    rooms: 2,
    bathrooms: 2,
    size_sqm: 120,
    floor: 15,
    year_built: 2018,
    monthly_rent: 0,
    total_floors: 25,
    has_garden: false,
    has_parking: true,
    has_pool: true,
    has_balcony: true,
    energy_class: "B",
    city: "Metroville",
    address: "123 High Street",
    zip_code: "10001",
    country: "USA",
    latitude: 40.7128,
    longitude: -74.0060,
    map_url: "https://maps.google.com",
    start_date: "2023-10-01T10:00:00Z",
    end_date: "2024-12-31T23:59:59Z",
    user_name: "Alice Johnson",
    user_email: "alice@example.com",
    user_phone: "555-0101",
    user_picture: "https://picsum.photos/seed/user1/100",
    years_of_experience: 8,
    broker_bio: "Specializing in luxury downtown properties with a client-first approach.",
    broker_name: "John Smith",
    broker_email: "john.smith@zenith.com",
    broker_phone: "555-0102",
    broker_picture: "https://picsum.photos/seed/broker1/100",
    agency_name: "Prestige Properties",
    agency_email: "contact@prestigeprop.com",
    agency_phone: "555-0103",
    agency_picture: "https://picsum.photos/seed/agency1/100",
    listing_status: "Active"
  },
  {
    id: 2,
    title: "Cozy Suburban Family Home",
    description: "Charming family home with a large backyard, perfect for summer barbecues. Located in a quiet, friendly neighborhood with excellent schools.",
    property_type: "House",
    listing_type: "For Sale",
    start_price: 450000,
    status: "Active",
    rooms: 4,
    bathrooms: 3,
    size_sqm: 200,
    floor: 1,
    year_built: 1995,
    monthly_rent: 0,
    total_floors: 2,
    has_garden: true,
    has_parking: true,
    has_pool: false,
    has_balcony: true,
    energy_class: "C",
    city: "Greenwood",
    address: "456 Oak Avenue",
    zip_code: "54321",
    country: "USA",
    latitude: 34.0522,
    longitude: -118.2437,
    map_url: "https://maps.google.com",
    start_date: "2023-09-15T09:00:00Z",
    end_date: "2024-11-30T23:59:59Z",
    user_name: "Bob Williams",
    user_email: "bob@example.com",
    user_phone: "555-0201",
    user_picture: "https://picsum.photos/seed/user2/100",
    years_of_experience: 12,
    broker_bio: "A seasoned real estate professional dedicated to finding your family's dream home.",
    broker_name: "Jane Doe",
    broker_email: "jane.doe@zenith.com",
    broker_phone: "555-0202",
    broker_picture: "https://picsum.photos/seed/broker2/100",
    agency_name: "Homestead Realty",
    agency_email: "info@homestead.com",
    agency_phone: "555-0203",
    agency_picture: "https://picsum.photos/seed/agency2/100",
    listing_status: "Active"
  },
  {
    id: 3,
    title: "Seaside Villa with Ocean View",
    description: "Experience luxury living in this magnificent seaside villa. Wake up to the sound of waves and enjoy stunning sunsets from your private balcony.",
    property_type: "Villa",
    listing_type: "For Rent",
    start_price: 5000,
    status: "Active",
    rooms: 5,
    bathrooms: 5,
    size_sqm: 350,
    floor: 1,
    year_built: 2020,
    monthly_rent: 5000,
    total_floors: 2,
    has_garden: true,
    has_parking: true,
    has_pool: true,
    has_balcony: true,
    energy_class: "A",
    city: "Coastal Paradise",
    address: "789 Shoreline Drive",
    zip_code: "90210",
    country: "USA",
    latitude: 33.7701,
    longitude: -118.1937,
    map_url: "https://maps.google.com",
    start_date: "2023-11-01T12:00:00Z",
    end_date: "2024-10-31T23:59:59Z",
    user_name: "Carol White",
    user_email: "carol@example.com",
    user_phone: "555-0301",
    user_picture: "https://picsum.photos/seed/user3/100",
    years_of_experience: 15,
    broker_bio: "Expert in high-end coastal properties and luxury rentals.",
    broker_name: "Michael Brown",
    broker_email: "michael.brown@zenith.com",
    broker_phone: "555-0302",
    broker_picture: "https://picsum.photos/seed/broker3/100",
    agency_name: "Oceanfront Estates",
    agency_email: "sales@oceanfront.com",
    agency_phone: "555-0303",
    agency_picture: "https://picsum.photos/seed/agency3/100",
    listing_status: "Active"
  }
];
